{{- $_ := set .Values "images" .Values.global.images }}
{{- $context := . }}
{{- $dependencies := .Values.dependencies.vpp }}
# host_os is a mandatory field
{{- $_ := required ".Values.global.node.host_os must be specified, valid values are ubuntu, centos" .Values.global.node.host_os }}{{- $host_os := .Values.global.node.host_os }}
{{- $uio_driver := .Values.global.tungsten_env_vpp.DPDK_UIO_DRIVER | default "uio_pci_generic" }}

{{- $serviceAccountName := "vpp" }}
{{ tuple $context $dependencies $serviceAccountName | include "helm-toolkit.snippets.kubernetes_pod_rbac_serviceaccount" }}
{{ tuple $context $serviceAccountName | include "helm-toolkit.snippets.kubernetes_pod_rbac_csr_role" }}
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: tungsten-vpp
spec:
{{ tuple $context "vpp-datapath" | include "helm-toolkit.snippets.kubernetes_upgrades_daemonset" | indent 2 }}
  template:
    metadata:
      labels:
{{ tuple $context "atsgen" "vpp-datapath" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
      annotations:
        configmap-hash: {{ tuple "configmap-env.yaml" $context | include "helm-toolkit.utils.hash" }}
    spec:
      serviceAccountName: {{ $serviceAccountName }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .Values.labels.vpp.node_selector_key }}
                operator: In
                values:
                - {{ .Values.labels.vpp.node_selector_value }}
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      imagePullSecrets:
        - name: contrail-vrouter-docker-secret
      initContainers:
{{ tuple $context $dependencies nil | include "helm-toolkit.snippets.kubernetes_entrypoint_init_container" | indent 8 }}
        - name: node-init
          image: {{ .Values.global.images.tags.node_init | quote }}
          imagePullPolicy: {{ default "" .Values.global.images.imagePullPolicy | quote }}
          securityContext:
            privileged: true
          env:
          - name: CONTRAIL_STATUS_IMAGE
            value: {{ .Values.global.images.tags.contrail_status | quote }}
          envFrom:
          - configMapRef:
              name: tungsten-vpp
          volumeMounts:
          - mountPath: /host/usr/bin
            name: host-usr-bin
          - mountPath: /etc/contrail/ssl
            name: ssl-dir
          - mountPath: /etc/sysctl.d
            name: host-sysctld-dir
        - name: vpp-init
          image: {{ .Values.global.images.tags.vpp_init | quote }}
          imagePullPolicy: {{ default "" .Values.global.images.imagePullPolicy | quote }}
          securityContext:
            privileged: true
          envFrom:
          - configMapRef:
              name: tungsten-vpp
          - configMapRef:
              name: contrail-xflow-configuration
{{- if .Values.manifests.configmap_vrouter_keystone }}
          - configMapRef:
              name: contrail-vrouter-keystone
{{- end }}
          env:
          - name: KEYSTONE_AUTH_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secrets.keystone.admin }}
                key: KEYSTONE_AUTH_ADMIN_PASSWORD
          volumeMounts:
          - mountPath: /lib/modules
            name: lib-modules
          - mountPath: /var/run
            name: var-run
          - mountPath: /host/etc/contrail
            name: host-etc-contrail
          - mountPath: /dev/hugepages
            name: hugepages
          - mountPath: /host/bin
            name: host-bin
{{- if .Values.manifests.job_kubernetes_cni_init }}
        - name: kubernetes-cni-init
          image: {{ .Values.global.images.tags.kubernetes_cni_init | quote }}
          imagePullPolicy: {{ default "" .Values.global.images.imagePullPolicy | quote }}
          envFrom:
          - configMapRef:
              name: tungsten-vpp
          volumeMounts:
          - mountPath: /var/lib/contrail
            name: var-lib-contrail
          - mountPath: /host/etc_cni
            name: etc-cni
          - mountPath: /host/opt_cni_bin
            name: opt-cni-bin
          - mountPath: /host/log_cni
            name: contrail-log
            subPath: cni
{{- end }}
      containers:
        - name: vpp-datapath
          image: {{ .Values.global.images.tags.vpp | quote }}
          imagePullPolicy: {{ default "" .Values.global.images.imagePullPolicy | quote }}
          securityContext:
            privileged: true
          envFrom:
          - configMapRef:
              name: tungsten-vpp
          - configMapRef:
              name: contrail-xflow-configuration
{{- if .Values.manifests.configmap_vrouter_keystone }}
          - configMapRef:
              name: contrail-vrouter-keystone
{{- end }}
          env:
          - name: KEYSTONE_AUTH_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secrets.keystone.admin }}
                key: KEYSTONE_AUTH_ADMIN_PASSWORD
          volumeMounts:
          - mountPath: /etc/
            name: mount-etc
          - mountPath: /lib/modules
            name: lib-modules
          - mountPath: /var/run
            name: var-run
          - mountPath: /var/lib/contrail
            name: var-lib-contrail
          - mountPath: /var/log/contrail
            name: contrail-log
          - mountPath: /etc/os-release
            name: os-release
          - mountPath: /etc/lsb-release
            name: lsb-release
          - mountPath: /dev
            name: host-dev
          - mountPath: /var/crashes
            name: var-crashes-vrouter
        - name: vpp-agent
          image: {{ .Values.global.images.tags.vpp_agent | quote }}
          imagePullPolicy: {{ default "" .Values.global.images.imagePullPolicy | quote }}
          securityContext:
            privileged: true
          envFrom:
          - configMapRef:
              name: tungsten-vpp
          - configMapRef:
              name: contrail-xflow-configuration
{{- if .Values.manifests.configmap_vrouter_keystone }}
          - configMapRef:
              name: contrail-vrouter-keystone
{{- end }}
          env:
          - name: KEYSTONE_AUTH_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secrets.keystone.admin }}
                key: KEYSTONE_AUTH_ADMIN_PASSWORD
          volumeMounts:
          - mountPath: /var/lib/contrail/
            name: var-lib-contrail
          - mountPath: /var/log/contrail/
            name: contrail-log
          - mountPath: /var/run
            name: var-run
          - mountPath: /var/crashes
            name: var-crashes-vrouter
          - mountPath: /host/bin
            name: host-bin
          - mountPath: /dev
            name: host-dev
          - mountPath: /etc/contrail/ssl
            name: ssl-dir
{{- if eq $host_os "centos"}}
          - mountPath: /etc/sysconfig/network-scripts
            name: network-scripts
{{- end }}
        - name: vpp-nodemgr
          image: {{ .Values.global.images.tags.nodemgr | quote }}
          imagePullPolicy: {{ default "" .Values.global.images.imagePullPolicy | quote }}
          envFrom:
          - configMapRef:
              name: tungsten-vpp
          - configMapRef:
              name: contrail-xflow-configuration
{{- if .Values.manifests.configmap_vrouter_keystone }}
          - configMapRef:
              name: contrail-vrouter-keystone
{{- end }}
          env:
          - name: NODE_TYPE
            value: vrouter
          - name: DOCKER_HOST
            value: "unix://mnt/docker.sock"
          - name: KEYSTONE_AUTH_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secrets.keystone.admin }}
                key: KEYSTONE_AUTH_ADMIN_PASSWORD
          volumeMounts:
          - mountPath: /mnt/docker.sock
            name: docker-unix-socket
          - mountPath: /var/log/contrail/
            name: contrail-log
          - mountPath: /var/crashes
            name: var-crashes-vrouter
          - mountPath: /etc/contrail/ssl
            name: ssl-dir
      volumes:
{{- if eq $host_os "centos"}}
      - name: network-scripts
        hostPath:
          path: /etc/sysconfig/network-scripts
{{- end }}
      - name: docker-unix-socket
        hostPath:
          path: /var/run/docker.sock
          type: Socket
      - name: var-run
        hostPath:
          path: /var/run
      - name: usr-src
        hostPath:
          path: /usr/src
      - name: lib-modules
        hostPath:
          path: /lib/modules
      - name: var-lib-contrail
        hostPath:
          path: /var/lib/contrail
      - name: contrail-log
        hostPath:
          path: /var/log/contrail
      - name: os-release
        hostPath:
          path: /usr/lib/os-release
      - name: lsb-release
        hostPath:
          path: /etc/lsb-release
      - name: mount-etc
        hostPath:
          path: /etc
      - name: hugepages
        hostPath:
          path: /dev/hugepages
      - name: var-crashes-vrouter
        hostPath:
          path: /var/crashes
      - name: host-bin
        hostPath:
          path: /bin
      - name: host-etc-contrail
        hostPath:
          path: /etc/contrail
      - name: host-usr-bin
        hostPath:
          path: {{ .Values.volumeMounts.host_usr_bin.hostPath }}
      - name: host-dev
        hostPath:
          path: /dev
      - name: ssl-dir
        hostPath:
          path: /etc/contrail/ssl
      - name: host-sysctld-dir
        hostPath:
          path: /etc/sysctl.d
{{- if .Values.manifests.job_kubernetes_cni_init }}
      - name: etc-cni
        hostPath:
          path: /etc/cni
      - name: opt-cni-bin
        hostPath:
          path: /opt/cni/bin
{{- end }}

